
# username: 您的的用户名(一般是手机号码)
username: "13600070000"

# password: 密码
password: "xxxxxxxx"

# date: 挂号日期
date: "2018-11-11"


# hospitalId: 医院id
hospitalId: "102"

# departmentId: 科室id
departmentId: "200039686"

# 关于如何获取 hospitalId 和 departmentId
# 1. 打开挂号页面
# 2. 假设地址栏中地址是 http://www.bjguahao.gov.cn/dpt/appoint/162-200002248.htm
# 3. 其中 162 是 hospitalId
# 4. 其中 200002248 是 departmentId


# 需要挂早上的号请填写1  需要挂下午的号请填写2
dutyCode: "1"

# patientName: 患者姓名
# 若是自己挂号可为空
patientName: "唐僧"

# 就诊卡号
hospitalCardId: ""

# 医保卡号
medicareCardId: "12222222"

# 患儿身份证
childrenIdNo: "110104201906124028"

# 患儿证件 1：身份证　　　　2:其他
cidType: "1"

# 患儿生日
childrenBirthday:  "2019-06-27"


# 性别　1:男   2:女
childrenGender:  "2"


# 保险类型
# 1:医保
# 8:一老一小
# 10:自费
reimbursementType: "8"

# doctorName: 医生姓名
# 不填写的话默认选最好的医生
# 填写后若这个医生没有号，会自动选其余号中最好的医生
doctorName: ""

# DebugLevel: 调试等级
# 支持的调试等级有 debug/info/warning/error/critical
DebugLevel: "info"

#使用ios短信和mac电脑接收验证码
useIMessage: "false"

# 是否使用 QPython3.6 运行本脚本
useQPython3: "false"

#使用短信转发助手和内建接收器接收验证码
useMsgForward:  "true"
